version: '3'

services:
  portainer:
    image: 'portainer/portainer-ce:2.9.0-alpine'
    ports:
      - '9443:9443'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data