version: '3'

#use docker volumes
#volumes:
#  traefik-ssl-certs:
#    driver: local

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080"  # Don't do this in production!
    volumes:
      # update this to docker volumes if deploy on swarm
      - ${ROOT_PATH}/config:/etc/traefik
      - ${ROOT_PATH}/certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro